M48
; DRILL file {KiCad 9.0.7} date 2026-03-17T16:13:25+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-17T16:13:25+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X124.58Y-87.93
X124.58Y-93.71
T2
X121.1Y-53.2
X121.1Y-108.6
X189.1Y-53.2
X189.1Y-108.6
M30
